# Generated by Django 3.2.9 on 2022-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220814_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.IntegerField(default='987654', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailid',
            field=models.CharField(default='example@gmail.com', max_length=50, unique=True),
        ),
    ]
